### ISSUE TITLE
Cannot build on Mac 10.6.2

### ISSUE THREAD

**Issue by LightGuard** [gradle-archive/gradle-intellij-gui#1]
Here's the exception:

$ gradle deploy -Didea.home=/Applications/IntelliJ\ IDEA\ 9.0.app/

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/jporter/java_libraries/gradle-idea-plugin/intellij-plugin/build.gradle' line: 142
- What went wrong:
  A problem occurred evaluating root project 'intellij-plugin'.
  Cause: Could not find property 'open-api.home' on root project 'intellij-plugin'.
- Try:
  Run with -s or -d option to get more details. Run with -S option to get the full (very verbose) stacktrace.

BUILD FAILED

Total time: 2.694 secs

**Comment by hansd** [comment]
Something like the following worked for me:

`gradle build -Didea.home=/home/hd/java/idea-IU-93.13 -Dgradle.home=/home/hd/java/gradle -Dopen-api.home=/home/hd/java/gradle/lib`
