### ISSUE TITLE
Getting "Cannot load project" error in Android Studio

### ISSUE THREAD

**Issue by javageek68** [gradle-archive/gradle-intellij-gui#11]
This is the full error message.

Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/jetbrains/plugins/gradle/util/GradleLibraryManager [Plugin: Gradle GUI]

I see this right after I install the plugin, restart, and load a project.

I'm running Android Studio 1.5.1 and Gradle GUI 1.7

**Comment by EdwardC2016** [comment]
ok so what did you do because I am having the same problem with the latest version 2.2.3 i am running windows 7..64bt.. what can I do

**Comment by javageek68** [comment]
Sorry for the very late reply.  This project runs in Visual Studio not Android Studio.
