### ISSUE TITLE
Changing GRADLE_HOME is not picked up.

### ISSUE THREAD

**Issue by hansd** [gradle-archive/gradle-intellij-gui#2]
The plugin threw an exception with the latest Gradle build. The reason for that was in the open-api. I have fixed the open-api and installed a new Gradle version. The change was not picked up. I had to go to the IntelliJ cache and removed all intellij-plugin related files. Then I restarted Idea. Now everything worked.

**Comment by gradle** [comment]
I didn't realize that the gradle-open-api is of course shipped with the plugin. So I had to use a new version of the plugin.
